api:
  url: https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=395&date=09-05-2021

jobs:
  cron: '*/15 * * * * *'

twilio:
  accountId: AC49c3fffd77ac2c66b75bac6a9444941f
  authToken: e10e0e882be8bd98c73747d6139f358d

cowin-portal:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJiZjliNDk1OC02MmYxLTQ4MDctOGI1YS03ZGU4YzdkNjc2NDMiLCJ1c2VyX2lkIjoiYmY5YjQ5NTgtNjJmMS00ODA3LThiNWEtN2RlOGM3ZDY3NjQzIiwidXNlcl90eXBlIjoiQkVORUZJQ0lBUlkiLCJtb2JpbGVfbnVtYmVyIjo5MTc1NDc5ODcwLCJiZW5lZmljaWFyeV9yZWZlcmVuY2VfaWQiOjQ4NzgxNzQyOTY5NDUwLCJzZWNyZXRfa2V5IjoiYjVjYWIxNjctNzk3Ny00ZGYxLTgwMjctYTYzYWExNDRmMDRlIiwidWEiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvOTAuMC40NDMwLjkzIFNhZmFyaS81MzcuMzYiLCJkYXRlX21vZGlmaWVkIjoiMjAyMS0wNS0xMFQwODoyOTo0Ni4yMDlaIiwiaWF0IjoxNjIwNjM1Mzg2LCJleHAiOjE2MjA2MzYyODZ9.x4q3x6Ngi1plCTE4IF2vKBrhEtbFWWJl6Z7G17_wrJc
